### ISSUE TITLE
Add support for RFC1950?

### ISSUE THREAD

**Issue by maz-1** [zerkman/zzlib#1]
I guess this library can only decompress RFC1952(aka gzip) and RFC1951(deflate) compressed data right?
How about adding RFC1950(zlib)?

**Comment by zerkman** [comment]
This could be done indeed. Do you plan to use it to implement the decoding of specific files ? like PNG or so ?

**Comment by maz-1** [comment]
I am trying to decompress some files in proprietary format, which are compressed in RFC1950 algorithm

**Comment by zerkman** [comment]
I have added basic support for RFC1950. For now, no checksum verification is done, and there is no support for a preset dictionary. Please tell me if you manage to use it.

**Comment by maz-1** [comment]
Thanks! Works like a charm!

**Comment by zerkman** [comment]
Glad you were able to use it. Closing the issue now.
