### ISSUE TITLE
Consideration of file data descriptor - workaround

### ISSUE THREAD

**Issue by zballito** [zerkman/zzlib#6]
Hi,
zzlib source code tells that data descriptor are not considered, This is problematic in some use case i met. Here after a proposal (for file zzlib-bit32.lua but applicable, i suppose, to zzlib-bwo.lua too), this proposal include the workaround about crc32 signed (i apologize for this late post knowing you update recently zzlib)

function zzlib.unzip(buf,filename)
  local p = 1
  local quit = false
  while not quit do
    local head = buf:int4le(p)
    if head == 0x04034b50 then
      -- local file header signature
      local flag = buf:int2le(p+6)
      local method = buf:int2le(p+8)
      local crc = buf:int4le(p+14)
      local csize = buf:int4le(p+18)
      local namelen = buf:int2le(p+26)
      local extlen = buf:int2le(p+28)
      local name = buf:sub(p+30,p+29+namelen)
--ADD-1 >>
      local NxtHdrPos=-1 -- init with out of range value
      p = p+30+namelen+extlen
--ADD-1 <<
      if bit.band(flag,1) ~= 0 then
        error("no support for encrypted files")
      elseif method ~= 8 and method ~= 0 then
        error("unsupported compression method")
      elseif bit.band(flag,8) ~= 0 then
--DEL-1 >>
      -- error("no support for the data descriptor record")
--DEL-1 <<
--ADD-2 >>
        -- SOURCES
        -- [0] https://stackoverflow.com/questions/38437826/how-to-create-zip-file-with-data-descriptor-section
        -- [1] https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT
        -- [2] https://users.cs.jmu.edu/buchhofp/forensics/formats/pkzip.html
        NxtHdrPos = string.find( buf, '\x50\x4b\x03\x04', p, true ) -- look ahead to get the signature that starts the next local header file
        if( NxtHdrPos==nil ) then error('unable to find '..filename.. 'into the zip' )
        else
          local DataDescrPos = NxtHdrPos-12 -- jump back to DataDescriptor Head regarding its size (in bytes) see [1] paragraph 4.3.9
          crc = buf:int4le(DataDescrPos) -- overwrite previous crc that is null, see [2] paragraph Data descriptor
          csize = buf:int4le(DataDescrPos+4) -- overwrite previous size that is null, see [2] paragraph Data descriptor
        end
--ADD-2 <<
      end
      
      if name == filename then
        local result
        if method == 0 then
          -- no compression
          result = buf:sub(p,p+csize-1)
        else
          -- DEFLATE compression
          local bs = bitstream_init(buf)
          bs.pos = p
          result = inflate_main(bs)
        end
--ADD >>
        local crc_res = crc32(result)
        if( crc_res<0 ) then
          local bitmax32 = 4294967296
          crc_res = bitmax32 + crc_res
        end
        if crc ~= crc_res then
--ADD <<
--DEL >>
      --if crc ~= crc32(result) then
--DEL <<
          error("checksum verification failed")
        end
        return result
      end
--DEL-2 >>
      -- p = p+csize
--DEL-2 <<
--ADD-3 >>
      if( bit.band(flag,8) ~= 0 )
      then p = NxtHdrPos
      else p = p+csize
      end
--ADD-3 <<
    else
      -- other header: end of the list of files
      quit = true
    end
  end
end

This "enhancement" allow usage of zzlib to decompress '.XLSX' file (that are zip file beyond extension) saved by Calc Application (from LibreOffice).
It worthly to note that '.XLSX' file saved by EXCEL application (from MSOffice) do not need this as they do not use data descriptor (different implement strategy granted by zip specification)

Feel free to adapt or reject this proposal it if you think is useless.

**Comment by zerkman** [comment]
Hi @zballito,

Thank you for the suggestion. I did not support data descriptors up to now since I did not know some specific file formats like .xlsx were actually using them.

I might be considering an adaptation of your code to be included in zzlib soon. However I already found a bug in your code : if the file you are looking for is the last in the zip archive, it will not be found since there is no local file header following it. I am not sure yet about how to reliably determine the location of the data descriptor for the last file. without decompressing the file.
Another issue, while very unlikely but possible, would be that the compressed data in a file contains the '\x50\x4b\x03\x04' byte subsequence which would lead the search to failure.
Therefore I am investigating about how to completely not rely on data  descriptors, probably using the data in the central directory record.

Prior to this I am planning to refactor the code so that most of the utility code (file format management, crc32, adler32) gets moved to zzlib.lua . Only the lua-implementation-specific deflate code will remain in separate files for performance reasons.

**Comment by zballito** [comment]
Hi,

I agree with your analyses on weaknesses of the work around. I will add more notes.

-if data descriptor is not found while the last data descriptor is crossed over, the code will follow its scanning on central directory (or whatever zone after) until the end of file.
      it is counter-performant (as the whole zip file is scanned) but the error message remain true, the file will be not found and the program returns.

-if during the whole scan bug 2 occurred, as you pointed, a similar byte sequence is found while it is not the start of a 'regular' descriptor,
      i had presumed that the following bytes after that similar sequence, do not match the checks of data descriptor. So checks will fail and program will returns.
      In this case error message point a cause like 'bad descriptor' while real cause is: 'file does not exist'. This case is acceptable in my tests conditions not in production.

-From what I remember, the ZIP specification does not tell how many descriptors are in, because, it allows 'stream compression'.
      That is, the informations on the compressed file (like crc32) are computed after the compression is done.
      And as you cannot go back to write them (cause the stream mode), you write them just after, that why descriptors 'at head' are not filled and they are given 'at foot'.

Thank again for your work.

SG

De : François Galea <notifications@github.com>
Envoyé : jeudi 2 avril 2020 01:58
À : zerkman/zzlib <zzlib@noreply.github.com>
Cc : GUILMEAU Sébastien <sebastien.guilmeau@irt-saintexupery.com>; Mention <mention@noreply.github.com>
Objet : Re: [zerkman/zzlib] Consideration of file data descriptor - workaround (#6)


Hi @zballito<https://github.com/zballito>,

Thank you for the suggestion. I did not support data descriptors up to now since I did not know some specific file formats like .xlsx were actually using them.

I might be considering an adaptation of your code to be included in zzlib soon. However I already found a bug in your code : if the file you are looking for is the last in the zip archive, it will not be found since there is no local file header following it. I am not sure yet about how to reliably determine the location of the data descriptor for the last file. without decompressing the file.
Another issue, while very unlikely but possible, would be that the compressed data in a file contains the '\x50\x4b\x03\x04' byte subsequence which would lead the search to failure.
Therefore I am investigating about how to completely not rely on data descriptors, probably using the data in the central directory record.

Prior to this I am planning to refactor the code so that most of the utility code (file format management, crc32, adler32) gets moved to zzlib.lua . Only the lua-implementation-specific deflate code will remain in separate files for performance reasons.

**Comment by zerkman** [comment]
I just did the refactoring and reimplemented the zip file exploration using the central directory record.
It seems to be working fine on .zip and .xlsx files.
Can you try the latest version and tell me if it works on your test cases ?

**Comment by zballito** [comment]
Yeap, sure, i will test the changes tonight or in worst case this week, if it is okay for you.

De : François Galea <notifications@github.com>
Envoyé : jeudi 2 avril 2020 15:37
À : zerkman/zzlib <zzlib@noreply.github.com>
Cc : GUILMEAU Sébastien <sebastien.guilmeau@irt-saintexupery.com>; Mention <mention@noreply.github.com>
Objet : Re: [zerkman/zzlib] Consideration of file data descriptor - workaround (#6)


I just did the refactoring and reimplemented the zip file exploration using the central directory record.
It seems to be working fine on .zip and .xlsx files.
Can you try the latest version and tell me if it works on your test cases ?

**Comment by zballito** [comment]
Hi,

I pass test on my set of zip files (that have descriptors before and after the compressed data),
they run without error returned and lead to same results that I had obtained with the proposed work arounds active.
So it's fine for me!

By the way, your excellent work is not referenced into Luarocks repository (so not visible by "mainstream Lua coders"), is it a choice?

Thanks a lot again.

**Comment by zerkman** [comment]
Thank you for testing and your feedback. Glad it works for you.

I did not really look into Luarocks. I will consider adding zzlib to it.

Cheers
